version: "3.9"
   
services:
  wedding-webapp:
    image: ${APP_REGISTRY}/${APP_IMAGE}:${APP_TAG}
    container_name: wedding-webapp
    command: python manage.py runserver 0.0.0.0:8000
    env_file: 
      - .env.local
    ports:
      - "8000:8000"
    volumes:
      - ./application:/application
    depends_on:
      - postgres
 
  postgres:
    image: postgres:13.3
    restart: always
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
      POSTGRES_USER: ${POSTGRES_USERNAME:?POSTGRES_USERNAME not set}
      POSTGRES_DB: ${POSTGRES_DATABASE:?POSTGRES_DATABASE not set}
      POSTGRES_INITDB_ARGS: "--encoding='UTF-8'"
    expose:
      - ${POSTGRES_PORT:?POSTGRES_PORT not set}

volumes:
  postgres: