name: wedding
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python==3.9             # PSF
  - pip==21.1.2             # MIT
  - pip:
    - autoflake==1.4        # MIT
    - black==21.5b2         # MIT
    - django==4.1           # BSD-3
    - isort==5.8.0          # MIT
    - psycopg2==2.9.6       # LGPL