version: "3.9"
   
services:
  webapp:
    image: $APP_REGISTRY/$APP_IMAGE:$APP_TAG
    container_name: webapp
    pull_policy: always
    command: gunicorn basic_app.wsgi:application --bind 0.0.0.0:8000
    env_file: 
      - .env
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13.3
    container_name: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
      POSTGRES_USER: ${POSTGRES_USERNAME:?POSTGRES_USERNAME not set}
      POSTGRES_DB: ${POSTGRES_DATABASE:?POSTGRES_DATABASE not set}
      POSTGRES_INITDB_ARGS: "--encoding='UTF-8'"
    expose:
      - ${POSTGRES_PORT:?POSTGRES_PORT not set}

volumes:
  postgres:
    